language: php
php:
  - 5.6
  - 7.0
mysql:
  database: activecollab_database_structure_test
  username: root
  encoding: utf8mb4
install:
  - composer install --dev
  - phpunit --version
before_script:
  - mysql -e 'create database activecollab_database_structure_test'
script: phpunit -c test/phpunit.xml