sudo: true
language: php
php:
  - 5.6
  - '7'
services:
  - mysql
install: composer install --dev
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database activecollab_database_structure_test'
script: phpunit
