language: php
php:
  - 5.6
  - 7
mysql:
  database: activecollab_database_structure_test
  username: root
  encoding: utf8mb4
install:
  - composer install --dev
  - phpunit --version
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database activecollab_database_structure_test'
script: phpunit